---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.', '-f${_DOCKERFILE}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["tag", "eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "eu.gcr.io/$PROJECT_ID/$REPO_NAME:latest"]
​
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/${_KUBERNETES_DEPLOYMENT}', '${_CONTAINER_NAME}=eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
    env:
    - CLOUDSDK_CONTAINER_CLUSTER=${_KUBERNETES_CLUSTER}
    - CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'kms'
    - 'decrypt'
    - '--ciphertext-file=${_KMS_KEYNAME}.enc'
    - '--plaintext-file=${_KMS_KEYNAME}'
    - '--location=global'
    - '--keyring=cloud-build'
    - '--key=cloudbuild-encrypt'
    - '--project=${_PROJECT}'

  - name: 'gcr.io/secret-fleuri-project/cloud_build_add'
    env:
    - 'CREDENTIALS=/workspace/${_KMS_KEYNAME}'
    - 'PROJECT=${_PROJECT}'
    - 'CLUSTER=${_KUBERNETES_CLUSTER}'
    - 'REGION=${_COMPUTE_ZONE}'
​
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', "eu.gcr.io/$PROJECT_ID/$REPO_NAME:latest"]